In [2]:
import numpy as np

## 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

In [10]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.

In [24]:
a1 = a.reshape(2,6)
a2 = a.reshape(3,4)
a3 = a.reshape(4,3)
a4 = a.reshape(6,2)
a5 = a.reshape(12,1)

## 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).

In [27]:
a1 = a.reshape(2,-1)
a2 = a.reshape(3,-1)
a3 = a.reshape(4,-1)
a4 = a.reshape(-1,2)
a5 = a.reshape(-1,1)

## 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: 
Думаю, нельзя. Доступ к элементам в этом случае будет с использованием двумерной индексации - т.е. такой массив - частный случай двумерного массива.

## 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.

In [35]:
arr = np.random.randn(3,4)
arr_2 = arr.flatten()
arr.size == arr_2.size

True

## 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.

In [37]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?

In [55]:
b = np.zeros((1, 10), dtype='int32')
b[0] = np.arange(20, 1, -2)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Разница между массивами a и b в том, что первый - одномерный, второй двумерный.

## 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [15]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [21]:
# Видимо, имелось в виду от 0 до 12 невключительно, потому что иначе решейпить массив не получится без удаления элементов.
a = np.arange(0, 12, 1)
A = a.reshape((4, 3))
At = A.T
At
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Матрица B имеет размер (4, 4).

In [26]:
np.linalg.det(B)

0.0

Обратную матрицу от матрицы B посчитать нельзя потому что определитель матрицы B равен нулю.

## 10

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [154]:
np.random.seed(42)

## 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

In [91]:
c = np.random.randint(0, 16, 16)
c

array([ 1,  5,  9,  3,  9, 14,  7, 12, 12,  3,  3,  0, 11,  2,  7, 15])

## 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [92]:
C = c.reshape((4,4))
C

array([[ 1,  5,  9,  3],
       [ 9, 14,  7, 12],
       [12,  3,  3,  0],
       [11,  2,  7, 15]])

In [93]:
D = C * 10 + B
D

array([[ 15,  64, 113,  62],
       [104, 190, 156, 242],
       [143, 116, 179, 212],
       [142, 142, 282, 452]])

In [94]:
np.linalg.det(D) # Определитель.
np.linalg.matrix_rank(D) # Ранг матрицы.
D_inv = np.linalg.inv(D) # Обратная матрица.
D_inv

array([[-0.00834886, -0.00261463,  0.01355732, -0.00381368],
       [ 0.00151895,  0.00967789, -0.00345456, -0.0037696 ],
       [ 0.01204258, -0.00595528,  0.00288639,  0.0001828 ],
       [-0.00536762,  0.00149648, -0.00497468,  0.0044807 ]])

## 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [146]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 1.],
       [0., 1., 0., 1.]])

In [150]:
E = np.where(D_inv == 1, B, C)
E

array([[  1,   5,  23,   3],
       [ 14,  50,   7,  12],
       [ 23,   3, 149, 212],
       [ 11, 122,   7, 302]])